apiVersion: apps/v1
kind: Deployment
metadata:
  name: crudapp-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      crudapp: web
  template:
    metadata:
      labels:
        crudapp: web
    spec:
      containers:
      - name: crudapp-site
        image: aravind43zz/crudapp_java:1.0
---
apiVersion: v1
kind: Service
metadata:
  name: crudapp-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    crudapp: web
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30030
